export { RenderMessageComponent, MagicText } from './components';
export {
  MagicTextRenderCaret,
  MagicTextRenderCitation,
  MagicTextRenderNode,
  MagicTextRenderTextSegment,
  type MagicTextCitationClickEvent,
  type MagicTextCitationRenderContext,
  type MagicTextLinkClickEvent,
  type MagicTextCaretContext,
  type MagicTextNodeRenderContext,
  type MagicTextTextSegmentRenderContext,
} from './components';
export {
  chatResource,
  type ChatResourceOptions,
  type ChatResourceRef,
  completionResource,
  type CompletionResourceOptions,
  type CompletionResourceRef,
  structuredChatResource,
  type StructuredChatResourceOptions,
  type StructuredChatResourceRef,
  structuredCompletionResource,
  type StructuredCompletionResourceOptions,
  type StructuredCompletionResourceRef,
  uiChatResource,
  type UiChatMessageOutput,
  type UiChatResourceOptions,
  type UiChatResourceRef,
  uiCompletionResource,
  type UiCompletionResourceOptions,
  type UiCompletionResourceRef,
} from './resources';
export { provideHashbrown, type ProvideHashbrownOptions } from './providers';
export {
  createRuntime,
  createRuntimeFunction,
  createTool,
  createToolJavaScript,
  createUiKit,
  exposeComponent,
  exposeMarkdown,
  injectImperativeJsonParser,
  injectMagicTextParser,
  injectJsonParser,
  type AngularSignalLike,
  type ComponentPropSchema,
  type CreateRuntimeOptions,
  type CreateToolJavaScriptOptions,
  type ExposeMarkdownConfig,
  type ExposeMarkdownBuiltInRendererConfig,
  type ExposeMarkdownCustomRendererConfig,
  type ExposedComponent,
  type MagicTextParserRef,
  type MagicTextExposeInputs,
  type MagicTextRendererComponentType,
  type UiKitInput,
  type UiKit,
  type UiKitOptions,
  type SignalLike,
  type TagNameRegistry,
  type UiAssistantMessage,
  type UiChatMessage,
  type UiChatSchema,
  type UiChatSchemaComponent,
  type UiErrorMessage,
  type UiUserMessage,
} from './utils';
