name: Nightly Integration Tests

on:
  workflow_dispatch:
  schedule:
    # Runs every night at 00:00 UTC (midnight)
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Test e2e
        run: npx nx run-many -t e2e --parallel=3
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}
          AZURE_ENDPOINT: ${{ secrets.AZURE_ENDPOINT }}
          AZURE_API_VERSION: ${{ secrets.AZURE_API_VERSION }}
          WRITER_API_KEY: ${{ secrets.WRITER_API_KEY }}
